-- begin PIZZERIA_PIZZA
create unique index IDX_PIZZERIA_PIZZA_UK_NAME on PIZZERIA_PIZZA (NAME) where DELETE_TS is null ^
-- end PIZZERIA_PIZZA
-- begin PIZZERIA_TOPPING
create unique index IDX_PIZZERIA_TOPPING_UK_NAME on PIZZERIA_TOPPING (NAME) where DELETE_TS is null ^
-- end PIZZERIA_TOPPING
-- begin PIZZERIA_PAYMENT
alter table PIZZERIA_PAYMENT add constraint FK_PIZZERIA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZERIA_ORDER(ID)^
create index IDX_PIZZERIA_PAYMENT_ON_ORDER on PIZZERIA_PAYMENT (ORDER_ID)^
-- end PIZZERIA_PAYMENT
-- begin PIZZERIA_ORDER
alter table PIZZERIA_ORDER add constraint FK_PIZZERIA_ORDER_ON_DELIVER_COURIER foreign key (DELIVER_COURIER_ID) references SEC_USER(ID)^
create unique index IDX_PIZZERIA_ORDER_UK_NUMBER_ on PIZZERIA_ORDER (NUMBER_) where DELETE_TS is null ^
create index IDX_PIZZERIA_ORDER_ON_DELIVER_COURIER on PIZZERIA_ORDER (DELIVER_COURIER_ID)^
-- end PIZZERIA_ORDER
-- begin PIZZERIA_ORDER_ITEM
alter table PIZZERIA_ORDER_ITEM add constraint FK_PIZZERIA_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references PIZZERIA_ORDER(ID)^
alter table PIZZERIA_ORDER_ITEM add constraint FK_PIZZERIA_ORDER_ITEM_ON_PIZZA foreign key (PIZZA_ID) references PIZZERIA_PIZZA(ID)^
create index IDX_PIZZERIA_ORDER_ITEM_ON_ORDER on PIZZERIA_ORDER_ITEM (ORDER_ID)^
create index IDX_PIZZERIA_ORDER_ITEM_ON_PIZZA on PIZZERIA_ORDER_ITEM (PIZZA_ID)^
-- end PIZZERIA_ORDER_ITEM
-- begin PIZZERIA_INGREDIENT
alter table PIZZERIA_INGREDIENT add constraint FK_PIZZERIA_INGREDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZERIA_TOPPING(ID)^
alter table PIZZERIA_INGREDIENT add constraint FK_PIZZERIA_INGREDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZERIA_PIZZA(ID)^
create index IDX_PIZZERIA_INGREDIENT_ON_TOPPING on PIZZERIA_INGREDIENT (TOPPING_ID)^
create index IDX_PIZZERIA_INGREDIENT_ON_PIZZA on PIZZERIA_INGREDIENT (PIZZA_ID)^
-- end PIZZERIA_INGREDIENT
