alter table PIZZERIA_INGREDIENT add constraint FK_PIZZERIA_INGREDIENT_ON_TOPPING foreign key (TOPPING_ID) references PIZZERIA_TOPPING(ID);
alter table PIZZERIA_INGREDIENT add constraint FK_PIZZERIA_INGREDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZERIA_PIZZA(ID);
create index IDX_PIZZERIA_INGREDIENT_ON_TOPPING on PIZZERIA_INGREDIENT (TOPPING_ID);
create index IDX_PIZZERIA_INGREDIENT_ON_PIZZA on PIZZERIA_INGREDIENT (PIZZA_ID);
