alter table PIZZERIA_ORDER add constraint FK_PIZZERIA_ORDER_ON_DELIVER foreign key (DELIVER_ID) references PIZZERIA_DELIVERY(ID);
create unique index IDX_PIZZERIA_ORDER_UK_NUMBER_ on PIZZERIA_ORDER (NUMBER_) where DELETE_TS is null ;
create index IDX_PIZZERIA_ORDER_ON_DELIVER on PIZZERIA_ORDER (DELIVER_ID);
