alter table PIZZERIA_ORDER add constraint FK_PIZZERIA_ORDER_ON_DELIVER_COURIER foreign key (DELIVER_COURIER_ID) references SEC_USER(ID);
create index IDX_PIZZERIA_ORDER_ON_DELIVER_COURIER on PIZZERIA_ORDER (DELIVER_COURIER_ID);
