alter table PIZZERIA_DELIVERY add constraint FK_PIZZERIA_DELIVERY_ON_COURIER foreign key (COURIER_ID) references SEC_USER(ID);
create index IDX_PIZZERIA_DELIVERY_ON_COURIER on PIZZERIA_DELIVERY (COURIER_ID);
