alter table PIZZERIA_PAYMENT add constraint FK_PIZZERIA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZERIA_ORDER(ID);
create index IDX_PIZZERIA_PAYMENT_ON_ORDER on PIZZERIA_PAYMENT (ORDER_ID);
