alter table PIZZERIA_ORDER_ITEM add constraint FK_PIZZERIA_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references PIZZERIA_ORDER(ID);
alter table PIZZERIA_ORDER_ITEM add constraint FK_PIZZERIA_ORDER_ITEM_ON_PIZZA foreign key (PIZZA_ID) references PIZZERIA_PIZZA(ID);
create index IDX_PIZZERIA_ORDER_ITEM_ON_ORDER on PIZZERIA_ORDER_ITEM (ORDER_ID);
create index IDX_PIZZERIA_ORDER_ITEM_ON_PIZZA on PIZZERIA_ORDER_ITEM (PIZZA_ID);
